### ISSUE TITLE
TypeError in CloudwatchLog

### ISSUE THREAD

**Issue by ghost** [AshanFernando/SESEmailForward#2]
After creating the stack I get this error message in my CloudWatch Logs

```
TypeError: Cannot read property 'from' of undefined
at exports.handler (/var/task/index.js:14:55)
```

This is line 14:
    headers += "Reply-To: "+msgInfo.mail.commonHeaders.**from**[0]+"\r\n";

**Comment by mpatters72** [comment]
If I hard-code from and to address, I get TypeError: Cannot read property 'Message' of undefined at exports.handler (/var/task/index.js:5:50)
