### ISSUE TITLE
Compatibility with Nodejs 10

### ISSUE THREAD

**Issue by jpadmin** [AshanFernando/SESEmailForward#7]
Hello Team,

Is the stack compatible with nodejs 10?

**Comment by AshanFernando** [comment]
@jpadmin Haven't tested yet on Nodejs 10 yet. I guess it should work.

**Comment by jpadmin** [comment]
@AshanFernando : yeah it works perfectly with nodejs 10. All I did was changing the execution environment in Lambda to v10
